'use client'

import { useState } from 'react'
import { Download, FileText, Presentation, Copy, Check, Loader2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { GeneratedOutput } from '@/lib/types'
import type { BrandingProfile } from '@/lib/types'
import { SLIDE_NAMES } from '@/lib/utils'

interface ExportButtonsProps {
  output: GeneratedOutput
  branding: BrandingProfile
  companyName: string
}

export function ExportButtons({ output, branding, companyName }: ExportButtonsProps) {
  const [exporting, setExporting] = useState<'pdf' | 'pptx' | 'copy' | null>(null)
  const [copied, setCopied] = useState(false)

  const handleCopyAll = async () => {
    const text = buildTextExport(output, companyName)
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExportPDF = async () => {
    setExporting('pdf')
    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const primaryColor = branding.colors[0] || '#7C3AED'
      const rgb = hexToRgbValues(primaryColor)

      const pageW = doc.internal.pageSize.getWidth()
      const pageH = doc.internal.pageSize.getHeight()
      const margin = 20

      // Helper to add a slide page
      const addSlide = (title: string, content: string[], slideNum: number, totalSlides: number) => {
        if (slideNum > 1) doc.addPage()

        // Header bar
        doc.setFillColor(rgb.r, rgb.g, rgb.b)
        doc.rect(0, 0, pageW, 18, 'F')

        // Slide number
        doc.setFontSize(10)
        doc.setTextColor(255, 255, 255)
        doc.text(`${slideNum} / ${totalSlides}`, pageW - margin, 12, { align: 'right' })

        // Title
        doc.setFontSize(22)
        doc.setTextColor(255, 255, 255)
        doc.text(title, margin, 12)

        // Content
        doc.setFontSize(12)
        doc.setTextColor(30, 27, 75)
        let y = 35
        for (const line of content) {
          if (line.startsWith('|')) continue // skip table rows (too complex for basic PDF)
          const wrapped = doc.splitTextToSize(`• ${line}`, pageW - margin * 2)
          if (y + wrapped.length * 7 > pageH - margin) break
          doc.text(wrapped, margin, y)
          y += wrapped.length * 7 + 3
        }

        // Footer
        doc.setFontSize(8)
        doc.setTextColor(180, 180, 180)
        doc.text(companyName, margin, pageH - 8)
        doc.text('Generated by PitchDeck Generator', pageW - margin, pageH - 8, { align: 'right' })
      }

      // Title page
      doc.setFillColor(rgb.r, rgb.g, rgb.b)
      doc.rect(0, 0, pageW, pageH, 'F')
      doc.setFontSize(36)
      doc.setTextColor(255, 255, 255)
      doc.text(companyName, pageW / 2, pageH / 2 - 20, { align: 'center' })
      doc.setFontSize(16)
      doc.setTextColor(200, 200, 255)
      doc.text('Pitch Deck', pageW / 2, pageH / 2, { align: 'center' })

      // Slide pages
      output.slides.forEach((slide, i) => {
        addSlide(slide.title, slide.content ?? slide.bullets ?? [], i + 1, output.slides.length)
      })

      // Talk Track page
      doc.addPage()
      doc.setFillColor(rgb.r, rgb.g, rgb.b)
      doc.rect(0, 0, pageW, 18, 'F')
      doc.setFontSize(20)
      doc.setTextColor(255, 255, 255)
      doc.text('Talk Track', margin, 12)
      doc.setFontSize(11)
      doc.setTextColor(30, 27, 75)
      const lines = doc.splitTextToSize(output.talkTrack || '', pageW - margin * 2)
      let y = 30
      for (const line of lines) {
        if (y > pageH - margin) { doc.addPage(); y = margin }
        doc.text(line, margin, y)
        y += 6
      }

      doc.save(`${companyName.replace(/\s+/g, '-')}-pitch-deck.pdf`)
    } catch (err) {
      console.error('PDF export error:', err)
      alert('PDF export failed. Please try Copy instead.')
    } finally {
      setExporting(null)
    }
  }

  const handleExportPPTX = async () => {
    setExporting('pptx')
    try {
      const pptxgen = (await import('pptxgenjs')).default
      const prs = new pptxgen()

      const primaryHex = branding.colors[0] || '7C3AED'
      const primaryClean = primaryHex.replace('#', '')
      const secondaryHex = (branding.colors[1] || '5B21B6').replace('#', '')

      prs.layout = 'LAYOUT_WIDE'

      // Define slide master
      prs.defineSlideMaster({
        title: 'BRAND_MASTER',
        bkgd: 'FFFFFF',
        objects: [
          // Bottom bar
          {
            rect: {
              x: 0, y: 7.0, w: '100%', h: 0.3,
              fill: { color: primaryClean },
            },
          },
          // Company name watermark
          {
            text: {
              text: companyName,
              options: {
                x: 0.3, y: 7.0, w: 3, h: 0.3,
                fontSize: 9, color: 'FFFFFF', valign: 'middle',
              },
            },
          },
        ],
        slideNumber: { x: 11.5, y: 7.0, color: 'FFFFFF', fontSize: 9 },
      })

      // Title slide
      const titleSlide = prs.addSlide({ masterName: 'BRAND_MASTER' })
      titleSlide.addShape(prs.ShapeType.rect, {
        x: 0, y: 0, w: '100%', h: '100%',
        fill: { color: primaryClean },
      })
      titleSlide.addText(companyName, {
        x: 1, y: 2, w: 10, h: 1.5,
        fontSize: 44, bold: true, color: 'FFFFFF', align: 'center',
      })
      titleSlide.addText((output.slides[0]?.content ?? output.slides[0]?.bullets ?? [])[0] || '', {
        x: 1, y: 3.8, w: 10, h: 0.8,
        fontSize: 18, color: 'E0D7FF', align: 'center',
      })

      // Content slides
      for (const slide of output.slides) {
        const s = prs.addSlide({ masterName: 'BRAND_MASTER' })

        // Title bar
        s.addShape(prs.ShapeType.rect, {
          x: 0, y: 0, w: '100%', h: 1.2,
          fill: { color: primaryClean },
        })
        s.addText(slide.title, {
          x: 0.4, y: 0, w: 11, h: 1.2,
          fontSize: 28, bold: true, color: 'FFFFFF', valign: 'middle',
        })

        // Bullets
        const bulletPoints = (slide.content ?? slide.bullets ?? [])
          .filter(b => !b.startsWith('|') && !b.includes('---'))
          .map(b => ({ text: b, options: { bullet: { type: 'bullet' as const } } }))

        if (bulletPoints.length > 0) {
          s.addText(bulletPoints, {
            x: 0.4, y: 1.5, w: 11.5, h: 5,
            fontSize: 16, color: '1E1B4B', valign: 'top',
            bullet: { type: 'bullet' },
          })
        }
      }

      // Talk track slide
      const ttSlide = prs.addSlide({ masterName: 'BRAND_MASTER' })
      ttSlide.addShape(prs.ShapeType.rect, {
        x: 0, y: 0, w: '100%', h: 1.2,
        fill: { color: secondaryHex },
      })
      ttSlide.addText('Talk Track', {
        x: 0.4, y: 0, w: 11, h: 1.2,
        fontSize: 28, bold: true, color: 'FFFFFF', valign: 'middle',
      })
      ttSlide.addText((output.talkTrack || '').slice(0, 800) + ((output.talkTrack || '').length > 800 ? '...' : ''), {
        x: 0.4, y: 1.5, w: 11.5, h: 5,
        fontSize: 11, color: '374151', valign: 'top',
        wrap: true,
      })

      await prs.writeFile({ fileName: `${companyName.replace(/\s+/g, '-')}-pitch-deck.pptx` })
    } catch (err) {
      console.error('PPTX export error:', err)
      alert('PPTX export failed. Please try PDF export instead.')
    } finally {
      setExporting(null)
    }
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        onClick={handleCopyAll}
        className={cn(
          'flex items-center gap-2 px-4 py-2 rounded-xl font-medium text-sm border transition-all',
          copied
            ? 'bg-green-50 border-green-200 text-green-700'
            : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-50 hover:border-gray-300'
        )}
      >
        {copied ? <Check size={15} /> : <Copy size={15} />}
        {copied ? 'Copied!' : 'Copy All'}
      </button>

      <button
        onClick={handleExportPDF}
        disabled={!!exporting}
        className={cn(
          'flex items-center gap-2 px-4 py-2 rounded-xl font-medium text-sm border transition-all',
          'bg-white border-gray-200 text-gray-700 hover:bg-red-50 hover:border-red-200 hover:text-red-700',
          'disabled:opacity-60 disabled:cursor-not-allowed'
        )}
      >
        {exporting === 'pdf' ? <Loader2 size={15} className="animate-spin" /> : <FileText size={15} />}
        Export PDF
      </button>

      <button
        onClick={handleExportPPTX}
        disabled={!!exporting}
        className={cn(
          'flex items-center gap-2 px-4 py-2 rounded-xl font-medium text-sm border transition-all',
          'bg-white border-gray-200 text-gray-700 hover:bg-orange-50 hover:border-orange-200 hover:text-orange-700',
          'disabled:opacity-60 disabled:cursor-not-allowed'
        )}
      >
        {exporting === 'pptx' ? <Loader2 size={15} className="animate-spin" /> : <Presentation size={15} />}
        Export PPTX
      </button>
    </div>
  )
}

function hexToRgbValues(hex: string) {
  const clean = hex.replace('#', '')
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  }
}

function buildTextExport(output: GeneratedOutput, companyName: string): string {
  const lines: string[] = [
    `PITCH DECK — ${companyName.toUpperCase()}`,
    '='.repeat(50),
    '',
    'TALK TRACK',
    '-'.repeat(30),
    output.talkTrack || '',
    '',
    '='.repeat(50),
    '',
    'PITCH DECK SLIDES',
    '-'.repeat(30),
  ]

  output.slides.forEach((slide, i) => {
    lines.push('')
    lines.push(`SLIDE ${i + 1}: ${slide.title} (${SLIDE_NAMES[slide.id] || slide.id})`)
    lines.push('')
    ;(slide.content ?? slide.bullets ?? []).forEach(bullet => lines.push(`• ${bullet}`))
    lines.push('')
    lines.push(`Visual: ${slide.visualSuggestion || slide.suggestedVisual || ''}`)
    lines.push('')
    if (slide.layoutSuggestion) lines.push(`Layout: ${slide.layoutSuggestion}`)
    if (slide.designNotes) {
      lines.push('Design Notes:')
      lines.push(`  Layout: ${slide.designNotes.layout}`)
      lines.push(`  Colors: ${slide.designNotes.colorUsage}`)
      lines.push(`  Fonts: ${slide.designNotes.fontHierarchy}`)
      lines.push(`  Logo: ${slide.designNotes.logoPlacement}`)
      lines.push(`  Style: ${slide.designNotes.visualStyle}`)
    }
    lines.push('-'.repeat(30))
  })

  lines.push('')
  lines.push('='.repeat(50))
  lines.push('QUICK IMPROVEMENTS')
  lines.push('-'.repeat(30))
  output.quickImprovements.forEach((item, i) => lines.push(`${i + 1}. ${item}`))

  lines.push('')
  lines.push('COACH NOTES')
  lines.push('-'.repeat(30))
  output.coachNotes.forEach((note, i) => lines.push(`${i + 1}. ${note}`))

  return lines.join('\n')
}
